"""empty message

Revision ID: b267fde88f26
Revises: 
Create Date: 2023-08-01 11:22:49.798213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b267fde88f26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_img',
    sa.Column('id_article_img', sa.String(length=36), nullable=False),
    sa.Column('img', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_article_img')
    )
    op.create_table('galleries',
    sa.Column('id_gallery', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('main_caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_gallery')
    )
    op.create_table('users',
    sa.Column('id_user', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=36), nullable=True),
    sa.Column('password', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('articles_bpi',
    sa.Column('id_article', sa.String(length=36), nullable=False),
    sa.Column('id_user', sa.String(length=36), nullable=True),
    sa.Column('id_img', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=72), nullable=True),
    sa.Column('article', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_img'], ['articles_img.id_article_img'], ),
    sa.PrimaryKeyConstraint('id_article')
    )
    op.create_table('galleries_img',
    sa.Column('id_gallery_img', sa.String(length=36), nullable=False),
    sa.Column('id_gallery', sa.String(length=36), nullable=True),
    sa.Column('file_name', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('is_main_img', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_gallery'], ['galleries.id_gallery'], ),
    sa.PrimaryKeyConstraint('id_gallery_img')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('galleries_img')
    op.drop_table('articles_bpi')
    op.drop_table('users')
    op.drop_table('galleries')
    op.drop_table('articles_img')
    # ### end Alembic commands ###
